### ISSUE TITLE
interesting lib,but I have some questions

### ISSUE THREAD

**Issue by imfox** [RonenNess/Shaku#1]
renderTarget clear(color.transparent) It's actually black 
buildText not support chinese and japanese, and maybe need origin parameter. origin defaults value is (0,0.5) maybe not so good
drawGroup requires additional transform parameter or can change SpritesGroup transform
the lib is very good, It fits my needs perfectly, thank you

**Comment by RonenNess** [comment]
Hi @imfox , thank you for the feedback!

1. This seems to be webgl / opengl limitation, as I use the basic clear method and I do set the alpha channel. I'll look into it though maybe there's a way to clear render targets which is I assume what you want. Pretty sure its something I did in the past with SDL..

2. In what way does it not support Japanese / Chinese? Characters placement, or is it something else? 

3. Since the result of buildText is a sprite group, you can iterate the sprites and set any property manually after creation, including origin. Use forEach for that, you can see an example here: https://ronenness.github.io/Shaku/demo/gfx_draw_text.html (the wavy animated text)

4. Not sure what you asked about the drawGroup transformation param, can you please explain?

Thanks!

**Comment by imfox** [comment]
Maybe I misunderstood. I think spritesGroup is a whole, which can adjust position, scale, oringin, rotate...
It is convenient to adjust the offset of some coordinates during batch drawing

**Comment by RonenNess** [comment]
Sprite group as a whole has its own transformation- rotation, scale and position. These transformations ends up as the parent transformation of the individual sprites in it, where each sprite has its own scale, rotation and position. 

So if for example you have two sprites with position -100,0 and 100,0, and they each rotate over time, and both sprites are under a group, you will see them rotate around their own center (assuming origin is 0.5,0.5), and positioned 200 px away from each other horizontally. If you move the group, they will move as a whole with it. If you rotate the group 90° they will rotate together around center point (position of the group), meaning they will now be vertical to each other (one above the other, 200px apart) while their local rotation around their own center will continue independently, as it belongs to their local transformations.

Does that answer your question?

**Comment by RonenNess** [comment]
@imfox closing this for now feel free to open if you have additional questions.  Thanks!

**Comment by imfox** [comment]
chinese character is too lot,but cannot generate dynamically now, Is there a better solution?
